# Generated by Django 4.2 on 2023-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField()),
                ('date2', models.DateTimeField()),
                ('date3', models.DateTimeField()),
                ('date4', models.DateTimeField()),
            ],
        ),
    ]
