# Generated by Django 4.2 on 2023-05-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimemodel',
            old_name='date1',
            new_name='Curr_End',
        ),
        migrations.RenameField(
            model_name='datetimemodel',
            old_name='date2',
            new_name='Curr_Start',
        ),
        migrations.RenameField(
            model_name='datetimemodel',
            old_name='date3',
            new_name='Prev_End',
        ),
        migrations.RenameField(
            model_name='datetimemodel',
            old_name='date4',
            new_name='Prev_Start',
        ),
    ]
